/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iAccessControlSol from './IAccessControl.sol/index.js';
export * as iComplianceSol from './ICompliance.sol/index.js';
export * as ierc20Sol from './IERC20.sol/index.js';
export * as ierc20MetadataSol from './IERC20Metadata.sol/index.js';
export * as iFeeMechanismSol from './IFeeMechanism.sol/index.js';