/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockProxySol from './MockProxy.sol/index.js';
export type { mockProxySol };
import type * as mockTokenSol from './MockToken.sol/index.js';
export type { mockTokenSol };