/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../../common.js"
  

  export interface EventsInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "ComplianceViolation" | "FeeCollected" | "ProposalCreated" | "ProposalExecuted" | "TokensBurned" | "TransferAnalytics" | "TransferBlocked" | "UserActivity"): EventFragment;

    

    
  }

  
    export namespace ComplianceViolationEvent {
      export type InputTuple = [account: AddressLike, reason: string];
      export type OutputTuple = [account: string, reason: string];
      export interface OutputObject {account: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeCollectedEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, amount: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [from: string, to: string, amount: bigint, fee: bigint];
      export interface OutputObject {from: string, to: string, amount: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCreatedEvent {
      export type InputTuple = [proposalId: BigNumberish, proposer: AddressLike, description: string];
      export type OutputTuple = [proposalId: bigint, proposer: string, description: string];
      export interface OutputObject {proposalId: bigint, proposer: string, description: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalExecutedEvent {
      export type InputTuple = [proposalId: BigNumberish, success: boolean];
      export type OutputTuple = [proposalId: bigint, success: boolean];
      export interface OutputObject {proposalId: bigint, success: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensBurnedEvent {
      export type InputTuple = [account: AddressLike, amount: BigNumberish, reason: string];
      export type OutputTuple = [account: string, amount: bigint, reason: string];
      export interface OutputObject {account: string, amount: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferAnalyticsEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, amount: BigNumberish, timestamp: BigNumberish, category: BytesLike];
      export type OutputTuple = [from: string, to: string, amount: bigint, timestamp: bigint, category: string];
      export interface OutputObject {from: string, to: string, amount: bigint, timestamp: bigint, category: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferBlockedEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, amount: BigNumberish, reason: string];
      export type OutputTuple = [from: string, to: string, amount: bigint, reason: string];
      export interface OutputObject {from: string, to: string, amount: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UserActivityEvent {
      export type InputTuple = [user: AddressLike, action: string, value: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [user: string, action: string, value: bigint, timestamp: bigint];
      export interface OutputObject {user: string, action: string, value: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Events extends BaseContract {
    
    connect(runner?: ContractRunner | null): Events;
    waitForDeployment(): Promise<this>;

    interface: EventsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'ComplianceViolation'): TypedContractEvent<ComplianceViolationEvent.InputTuple, ComplianceViolationEvent.OutputTuple, ComplianceViolationEvent.OutputObject>;
getEvent(key: 'FeeCollected'): TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
getEvent(key: 'ProposalCreated'): TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
getEvent(key: 'ProposalExecuted'): TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
getEvent(key: 'TokensBurned'): TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;
getEvent(key: 'TransferAnalytics'): TypedContractEvent<TransferAnalyticsEvent.InputTuple, TransferAnalyticsEvent.OutputTuple, TransferAnalyticsEvent.OutputObject>;
getEvent(key: 'TransferBlocked'): TypedContractEvent<TransferBlockedEvent.InputTuple, TransferBlockedEvent.OutputTuple, TransferBlockedEvent.OutputObject>;
getEvent(key: 'UserActivity'): TypedContractEvent<UserActivityEvent.InputTuple, UserActivityEvent.OutputTuple, UserActivityEvent.OutputObject>;

    filters: {
      
      'ComplianceViolation(address,string)': TypedContractEvent<ComplianceViolationEvent.InputTuple, ComplianceViolationEvent.OutputTuple, ComplianceViolationEvent.OutputObject>;
      ComplianceViolation: TypedContractEvent<ComplianceViolationEvent.InputTuple, ComplianceViolationEvent.OutputTuple, ComplianceViolationEvent.OutputObject>;
    

      'FeeCollected(address,address,uint256,uint256)': TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
      FeeCollected: TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
    

      'ProposalCreated(uint256,address,string)': TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
      ProposalCreated: TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
    

      'ProposalExecuted(uint256,bool)': TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
      ProposalExecuted: TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
    

      'TokensBurned(address,uint256,string)': TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;
      TokensBurned: TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;
    

      'TransferAnalytics(address,address,uint256,uint256,bytes32)': TypedContractEvent<TransferAnalyticsEvent.InputTuple, TransferAnalyticsEvent.OutputTuple, TransferAnalyticsEvent.OutputObject>;
      TransferAnalytics: TypedContractEvent<TransferAnalyticsEvent.InputTuple, TransferAnalyticsEvent.OutputTuple, TransferAnalyticsEvent.OutputObject>;
    

      'TransferBlocked(address,address,uint256,string)': TypedContractEvent<TransferBlockedEvent.InputTuple, TransferBlockedEvent.OutputTuple, TransferBlockedEvent.OutputObject>;
      TransferBlocked: TypedContractEvent<TransferBlockedEvent.InputTuple, TransferBlockedEvent.OutputTuple, TransferBlockedEvent.OutputObject>;
    

      'UserActivity(address,string,uint256,uint256)': TypedContractEvent<UserActivityEvent.InputTuple, UserActivityEvent.OutputTuple, UserActivityEvent.OutputObject>;
      UserActivity: TypedContractEvent<UserActivityEvent.InputTuple, UserActivityEvent.OutputTuple, UserActivityEvent.OutputObject>;
    
    };
  }