/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20BaseSol from './ERC20Base.sol/index.js';
export type { erc20BaseSol };
import type * as erc20MintBurnSol from './ERC20MintBurn.sol/index.js';
export type { erc20MintBurnSol };
import type * as erc20PausableSol from './ERC20Pausable.sol/index.js';
export type { erc20PausableSol };
import type * as erc20RolesSol from './ERC20Roles.sol/index.js';
export type { erc20RolesSol };