/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAccessControlSol from './IAccessControl.sol/index.js';
export type { iAccessControlSol };
import type * as iComplianceSol from './ICompliance.sol/index.js';
export type { iComplianceSol };
import type * as ierc20Sol from './IERC20.sol/index.js';
export type { ierc20Sol };
import type * as ierc20MetadataSol from './IERC20Metadata.sol/index.js';
export type { ierc20MetadataSol };
import type * as iFeeMechanismSol from './IFeeMechanism.sol/index.js';
export type { iFeeMechanismSol };