/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as analyticsHooksSol from './AnalyticsHooks.sol/index.js';
export type { analyticsHooksSol };
import type * as complianceLayerSol from './ComplianceLayer.sol/index.js';
export type { complianceLayerSol };
import type * as feeMechanismSol from './FeeMechanism.sol/index.js';
export type { feeMechanismSol };
import type * as governanceSol from './Governance.sol/index.js';
export type { governanceSol };
import type * as upgradeableProxySol from './UpgradeableProxy.sol/index.js';
export type { upgradeableProxySol };