/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockProxySol from './MockProxy.sol/index.js';
export * as mockTokenSol from './MockToken.sol/index.js';