/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IComplianceInterface extends Interface {
    getFunction(nameOrSignature: "blacklistAddress" | "isBlacklisted" | "setTransferLimit" | "transferLimit" | "whitelistAddress"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddressBlacklisted" | "AddressWhitelisted" | "TransferLimitUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'blacklistAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isBlacklisted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTransferLimit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferLimit', values?: undefined): string;
encodeFunctionData(functionFragment: 'whitelistAddress', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'blacklistAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isBlacklisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTransferLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelistAddress', data: BytesLike): Result;
  }

  
    export namespace AddressBlacklistedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AddressWhitelistedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferLimitUpdatedEvent {
      export type InputTuple = [oldLimit: BigNumberish, newLimit: BigNumberish];
      export type OutputTuple = [oldLimit: bigint, newLimit: bigint];
      export interface OutputObject {oldLimit: bigint, newLimit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ICompliance extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICompliance;
    waitForDeployment(): Promise<this>;

    interface: IComplianceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    blacklistAddress: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isBlacklisted: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    setTransferLimit: TypedContractMethod<
      [newLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferLimit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    whitelistAddress: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'blacklistAddress'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isBlacklisted'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setTransferLimit'): TypedContractMethod<
      [newLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferLimit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'whitelistAddress'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AddressBlacklisted'): TypedContractEvent<AddressBlacklistedEvent.InputTuple, AddressBlacklistedEvent.OutputTuple, AddressBlacklistedEvent.OutputObject>;
getEvent(key: 'AddressWhitelisted'): TypedContractEvent<AddressWhitelistedEvent.InputTuple, AddressWhitelistedEvent.OutputTuple, AddressWhitelistedEvent.OutputObject>;
getEvent(key: 'TransferLimitUpdated'): TypedContractEvent<TransferLimitUpdatedEvent.InputTuple, TransferLimitUpdatedEvent.OutputTuple, TransferLimitUpdatedEvent.OutputObject>;

    filters: {
      
      'AddressBlacklisted(address)': TypedContractEvent<AddressBlacklistedEvent.InputTuple, AddressBlacklistedEvent.OutputTuple, AddressBlacklistedEvent.OutputObject>;
      AddressBlacklisted: TypedContractEvent<AddressBlacklistedEvent.InputTuple, AddressBlacklistedEvent.OutputTuple, AddressBlacklistedEvent.OutputObject>;
    

      'AddressWhitelisted(address)': TypedContractEvent<AddressWhitelistedEvent.InputTuple, AddressWhitelistedEvent.OutputTuple, AddressWhitelistedEvent.OutputObject>;
      AddressWhitelisted: TypedContractEvent<AddressWhitelistedEvent.InputTuple, AddressWhitelistedEvent.OutputTuple, AddressWhitelistedEvent.OutputObject>;
    

      'TransferLimitUpdated(uint256,uint256)': TypedContractEvent<TransferLimitUpdatedEvent.InputTuple, TransferLimitUpdatedEvent.OutputTuple, TransferLimitUpdatedEvent.OutputObject>;
      TransferLimitUpdated: TypedContractEvent<TransferLimitUpdatedEvent.InputTuple, TransferLimitUpdatedEvent.OutputTuple, TransferLimitUpdatedEvent.OutputObject>;
    
    };
  }