/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AdvancedERC20Interface extends Interface {
    getFunction(nameOrSignature: "ANALYTICS_ROLE" | "BASIS_POINTS" | "BURNER_ROLE" | "CATEGORY_BURN" | "CATEGORY_FEE" | "CATEGORY_MINT" | "CATEGORY_STANDARD" | "COMPLIANCE_ROLE" | "DEFAULT_ADMIN_ROLE" | "GOVERNOR_ROLE" | "MAX_FEE" | "MINTER_ROLE" | "PAUSER_ROLE" | "allowance" | "approve" | "balanceOf" | "blacklistAddress" | "burn" | "burnFrom" | "burnRate" | "categoryVolume" | "createProposal" | "decimals" | "executeProposal" | "getCategoryVolume" | "getContractInfo" | "getMetrics" | "getProposal" | "getRoleAdmin" | "grantRole" | "hasRole" | "isBlacklisted" | "maxSupply" | "metrics" | "mint" | "name" | "pause" | "paused" | "proposalCount" | "proposals" | "quorum" | "renounceRole" | "resetMetrics" | "revokeRole" | "setBurnRate" | "setMaxSupply" | "setQuorum" | "setTransferFee" | "setTransferLimit" | "setTreasury" | "setVotingPeriod" | "supportsInterface" | "symbol" | "totalSupply" | "transfer" | "transferFee" | "transferFrom" | "transferLimit" | "treasury" | "unpause" | "version" | "vote" | "votingPeriod" | "whitelistAddress"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddressBlacklisted" | "AddressWhitelisted" | "Approval" | "BurnRateUpdated" | "FeeCollected" | "FeeUpdated" | "MaxSupplyUpdated" | "Paused" | "ProposalCreated(uint256,address,string)" | "ProposalCreated(uint256,address,string)" | "ProposalExecuted(uint256,bool)" | "ProposalExecuted(uint256,bool)" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "TokensBurned" | "Transfer" | "TransferAnalytics" | "TransferBlocked" | "TransferLimitUpdated" | "TreasuryUpdated" | "Unpaused" | "UserActivity" | "VoteCast"): EventFragment;

    encodeFunctionData(functionFragment: 'ANALYTICS_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'BASIS_POINTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'BURNER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'CATEGORY_BURN', values?: undefined): string;
encodeFunctionData(functionFragment: 'CATEGORY_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'CATEGORY_MINT', values?: undefined): string;
encodeFunctionData(functionFragment: 'CATEGORY_STANDARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'COMPLIANCE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'GOVERNOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MINTER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'blacklistAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'burn', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'burnFrom', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'burnRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'categoryVolume', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'createProposal', values: [string]): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCategoryVolume', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getContractInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMetrics', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isBlacklisted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'metrics', values?: undefined): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposalCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'quorum', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'resetMetrics', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setBurnRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMaxSupply', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setQuorum', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTransferFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTransferLimit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setVotingPeriod', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferLimit', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'votingPeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'whitelistAddress', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'ANALYTICS_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BASIS_POINTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BURNER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CATEGORY_BURN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CATEGORY_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CATEGORY_MINT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CATEGORY_STANDARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'COMPLIANCE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GOVERNOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MINTER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'blacklistAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'categoryVolume', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCategoryVolume', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContractInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMetrics', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isBlacklisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'metrics', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quorum', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resetMetrics', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBurnRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMaxSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setQuorum', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTransferFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTransferLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVotingPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votingPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelistAddress', data: BytesLike): Result;
  }

  
    export namespace AddressBlacklistedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AddressWhitelistedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BurnRateUpdatedEvent {
      export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
      export type OutputTuple = [oldRate: bigint, newRate: bigint];
      export interface OutputObject {oldRate: bigint, newRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeCollectedEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, amount: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [from: string, to: string, amount: bigint, fee: bigint];
      export interface OutputObject {from: string, to: string, amount: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MaxSupplyUpdatedEvent {
      export type InputTuple = [oldMaxSupply: BigNumberish, newMaxSupply: BigNumberish];
      export type OutputTuple = [oldMaxSupply: bigint, newMaxSupply: bigint];
      export interface OutputObject {oldMaxSupply: bigint, newMaxSupply: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCreated_uint256_address_string_Event {
      export type InputTuple = [proposalId: BigNumberish, proposer: AddressLike, description: string];
      export type OutputTuple = [proposalId: bigint, proposer: string, description: string];
      export interface OutputObject {proposalId: bigint, proposer: string, description: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCreated_uint256_address_string_Event {
      export type InputTuple = [proposalId: BigNumberish, proposer: AddressLike, description: string];
      export type OutputTuple = [proposalId: bigint, proposer: string, description: string];
      export interface OutputObject {proposalId: bigint, proposer: string, description: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalExecuted_uint256_bool_Event {
      export type InputTuple = [proposalId: BigNumberish, success: boolean];
      export type OutputTuple = [proposalId: bigint, success: boolean];
      export interface OutputObject {proposalId: bigint, success: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalExecuted_uint256_bool_Event {
      export type InputTuple = [proposalId: BigNumberish, success: boolean];
      export type OutputTuple = [proposalId: bigint, success: boolean];
      export interface OutputObject {proposalId: bigint, success: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensBurnedEvent {
      export type InputTuple = [account: AddressLike, amount: BigNumberish, reason: string];
      export type OutputTuple = [account: string, amount: bigint, reason: string];
      export interface OutputObject {account: string, amount: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferAnalyticsEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, amount: BigNumberish, timestamp: BigNumberish, category: BytesLike];
      export type OutputTuple = [from: string, to: string, amount: bigint, timestamp: bigint, category: string];
      export interface OutputObject {from: string, to: string, amount: bigint, timestamp: bigint, category: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferBlockedEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, amount: BigNumberish, reason: string];
      export type OutputTuple = [from: string, to: string, amount: bigint, reason: string];
      export interface OutputObject {from: string, to: string, amount: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferLimitUpdatedEvent {
      export type InputTuple = [oldLimit: BigNumberish, newLimit: BigNumberish];
      export type OutputTuple = [oldLimit: bigint, newLimit: bigint];
      export interface OutputObject {oldLimit: bigint, newLimit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryUpdatedEvent {
      export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
      export type OutputTuple = [oldTreasury: string, newTreasury: string];
      export interface OutputObject {oldTreasury: string, newTreasury: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UserActivityEvent {
      export type InputTuple = [user: AddressLike, action: string, value: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [user: string, action: string, value: bigint, timestamp: bigint];
      export interface OutputObject {user: string, action: string, value: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [proposalId: BigNumberish, voter: AddressLike, support: boolean, weight: BigNumberish];
      export type OutputTuple = [proposalId: bigint, voter: string, support: boolean, weight: bigint];
      export interface OutputObject {proposalId: bigint, voter: string, support: boolean, weight: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AdvancedERC20 extends BaseContract {
    
    connect(runner?: ContractRunner | null): AdvancedERC20;
    waitForDeployment(): Promise<this>;

    interface: AdvancedERC20Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ANALYTICS_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    BASIS_POINTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BURNER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    CATEGORY_BURN: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    CATEGORY_FEE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    CATEGORY_MINT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    CATEGORY_STANDARD: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    COMPLIANCE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    GOVERNOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MAX_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MINTER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    blacklistAddress: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    burn: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    burnFrom: TypedContractMethod<
      [account: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    burnRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    categoryVolume: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    createProposal: TypedContractMethod<
      [description: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    executeProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getCategoryVolume: TypedContractMethod<
      [category: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getContractInfo: TypedContractMethod<
      [],
      [[string, string, bigint, bigint, bigint, string, bigint, boolean] & {contractName: string, contractVersion: string, totalSupply_: bigint, maxSupply_: bigint, transferFee_: bigint, treasury_: string, burnRate_: bigint, isPaused: boolean }],
      'view'
    >
    

    
    getMetrics: TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {totalTransfers: bigint, totalVolume: bigint, uniqueUsers: bigint }],
      'view'
    >
    

    
    getProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {id: bigint, proposer: string, description: string, votesFor: bigint, votesAgainst: bigint, startTime: bigint, endTime: bigint, executed: boolean }],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isBlacklisted: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    maxSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    metrics: TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {totalTransfers: bigint, totalVolume: bigint, uniqueUsers: bigint }],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    proposalCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {id: bigint, proposer: string, description: string, votesFor: bigint, votesAgainst: bigint, startTime: bigint, endTime: bigint, executed: boolean }],
      'view'
    >
    

    
    quorum: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    resetMetrics: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setBurnRate: TypedContractMethod<
      [newRate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMaxSupply: TypedContractMethod<
      [newMaxSupply: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setQuorum: TypedContractMethod<
      [newQuorum: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTransferFee: TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTransferLimit: TypedContractMethod<
      [newLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setVotingPeriod: TypedContractMethod<
      [newPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferLimit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    version: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [proposalId: BigNumberish, support: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    votingPeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    whitelistAddress: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ANALYTICS_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'BASIS_POINTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BURNER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'CATEGORY_BURN'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'CATEGORY_FEE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'CATEGORY_MINT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'CATEGORY_STANDARD'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'COMPLIANCE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'GOVERNOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MINTER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'blacklistAddress'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burn'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burnFrom'): TypedContractMethod<
      [account: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burnRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'categoryVolume'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createProposal'): TypedContractMethod<
      [description: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'executeProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCategoryVolume'): TypedContractMethod<
      [category: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getContractInfo'): TypedContractMethod<
      [],
      [[string, string, bigint, bigint, bigint, string, bigint, boolean] & {contractName: string, contractVersion: string, totalSupply_: bigint, maxSupply_: bigint, transferFee_: bigint, treasury_: string, burnRate_: bigint, isPaused: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getMetrics'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {totalTransfers: bigint, totalVolume: bigint, uniqueUsers: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {id: bigint, proposer: string, description: string, votesFor: bigint, votesAgainst: bigint, startTime: bigint, endTime: bigint, executed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isBlacklisted'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'maxSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'metrics'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {totalTransfers: bigint, totalVolume: bigint, uniqueUsers: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'proposalCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {id: bigint, proposer: string, description: string, votesFor: bigint, votesAgainst: bigint, startTime: bigint, endTime: bigint, executed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'quorum'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resetMetrics'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBurnRate'): TypedContractMethod<
      [newRate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMaxSupply'): TypedContractMethod<
      [newMaxSupply: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setQuorum'): TypedContractMethod<
      [newQuorum: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTransferFee'): TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTransferLimit'): TypedContractMethod<
      [newLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVotingPeriod'): TypedContractMethod<
      [newPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferLimit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [proposalId: BigNumberish, support: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'votingPeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'whitelistAddress'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AddressBlacklisted'): TypedContractEvent<AddressBlacklistedEvent.InputTuple, AddressBlacklistedEvent.OutputTuple, AddressBlacklistedEvent.OutputObject>;
getEvent(key: 'AddressWhitelisted'): TypedContractEvent<AddressWhitelistedEvent.InputTuple, AddressWhitelistedEvent.OutputTuple, AddressWhitelistedEvent.OutputObject>;
getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'BurnRateUpdated'): TypedContractEvent<BurnRateUpdatedEvent.InputTuple, BurnRateUpdatedEvent.OutputTuple, BurnRateUpdatedEvent.OutputObject>;
getEvent(key: 'FeeCollected'): TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
getEvent(key: 'FeeUpdated'): TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
getEvent(key: 'MaxSupplyUpdated'): TypedContractEvent<MaxSupplyUpdatedEvent.InputTuple, MaxSupplyUpdatedEvent.OutputTuple, MaxSupplyUpdatedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'ProposalCreated(uint256,address,string)'): TypedContractEvent<ProposalCreated_uint256_address_string_Event.InputTuple, ProposalCreated_uint256_address_string_Event.OutputTuple, ProposalCreated_uint256_address_string_Event.OutputObject>;
getEvent(key: 'ProposalCreated(uint256,address,string)'): TypedContractEvent<ProposalCreated_uint256_address_string_Event.InputTuple, ProposalCreated_uint256_address_string_Event.OutputTuple, ProposalCreated_uint256_address_string_Event.OutputObject>;
getEvent(key: 'ProposalExecuted(uint256,bool)'): TypedContractEvent<ProposalExecuted_uint256_bool_Event.InputTuple, ProposalExecuted_uint256_bool_Event.OutputTuple, ProposalExecuted_uint256_bool_Event.OutputObject>;
getEvent(key: 'ProposalExecuted(uint256,bool)'): TypedContractEvent<ProposalExecuted_uint256_bool_Event.InputTuple, ProposalExecuted_uint256_bool_Event.OutputTuple, ProposalExecuted_uint256_bool_Event.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'TokensBurned'): TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'TransferAnalytics'): TypedContractEvent<TransferAnalyticsEvent.InputTuple, TransferAnalyticsEvent.OutputTuple, TransferAnalyticsEvent.OutputObject>;
getEvent(key: 'TransferBlocked'): TypedContractEvent<TransferBlockedEvent.InputTuple, TransferBlockedEvent.OutputTuple, TransferBlockedEvent.OutputObject>;
getEvent(key: 'TransferLimitUpdated'): TypedContractEvent<TransferLimitUpdatedEvent.InputTuple, TransferLimitUpdatedEvent.OutputTuple, TransferLimitUpdatedEvent.OutputObject>;
getEvent(key: 'TreasuryUpdated'): TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'UserActivity'): TypedContractEvent<UserActivityEvent.InputTuple, UserActivityEvent.OutputTuple, UserActivityEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;

    filters: {
      
      'AddressBlacklisted(address)': TypedContractEvent<AddressBlacklistedEvent.InputTuple, AddressBlacklistedEvent.OutputTuple, AddressBlacklistedEvent.OutputObject>;
      AddressBlacklisted: TypedContractEvent<AddressBlacklistedEvent.InputTuple, AddressBlacklistedEvent.OutputTuple, AddressBlacklistedEvent.OutputObject>;
    

      'AddressWhitelisted(address)': TypedContractEvent<AddressWhitelistedEvent.InputTuple, AddressWhitelistedEvent.OutputTuple, AddressWhitelistedEvent.OutputObject>;
      AddressWhitelisted: TypedContractEvent<AddressWhitelistedEvent.InputTuple, AddressWhitelistedEvent.OutputTuple, AddressWhitelistedEvent.OutputObject>;
    

      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'BurnRateUpdated(uint256,uint256)': TypedContractEvent<BurnRateUpdatedEvent.InputTuple, BurnRateUpdatedEvent.OutputTuple, BurnRateUpdatedEvent.OutputObject>;
      BurnRateUpdated: TypedContractEvent<BurnRateUpdatedEvent.InputTuple, BurnRateUpdatedEvent.OutputTuple, BurnRateUpdatedEvent.OutputObject>;
    

      'FeeCollected(address,address,uint256,uint256)': TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
      FeeCollected: TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
    

      'FeeUpdated(uint256,uint256)': TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
      FeeUpdated: TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
    

      'MaxSupplyUpdated(uint256,uint256)': TypedContractEvent<MaxSupplyUpdatedEvent.InputTuple, MaxSupplyUpdatedEvent.OutputTuple, MaxSupplyUpdatedEvent.OutputObject>;
      MaxSupplyUpdated: TypedContractEvent<MaxSupplyUpdatedEvent.InputTuple, MaxSupplyUpdatedEvent.OutputTuple, MaxSupplyUpdatedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    
'ProposalCreated(uint256,address,string)': TypedContractEvent<ProposalCreated_uint256_address_string_Event.InputTuple, ProposalCreated_uint256_address_string_Event.OutputTuple, ProposalCreated_uint256_address_string_Event.OutputObject>;
'ProposalCreated(uint256,address,string)': TypedContractEvent<ProposalCreated_uint256_address_string_Event.InputTuple, ProposalCreated_uint256_address_string_Event.OutputTuple, ProposalCreated_uint256_address_string_Event.OutputObject>;
'ProposalExecuted(uint256,bool)': TypedContractEvent<ProposalExecuted_uint256_bool_Event.InputTuple, ProposalExecuted_uint256_bool_Event.OutputTuple, ProposalExecuted_uint256_bool_Event.OutputObject>;
'ProposalExecuted(uint256,bool)': TypedContractEvent<ProposalExecuted_uint256_bool_Event.InputTuple, ProposalExecuted_uint256_bool_Event.OutputTuple, ProposalExecuted_uint256_bool_Event.OutputObject>;

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'TokensBurned(address,uint256,string)': TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;
      TokensBurned: TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'TransferAnalytics(address,address,uint256,uint256,bytes32)': TypedContractEvent<TransferAnalyticsEvent.InputTuple, TransferAnalyticsEvent.OutputTuple, TransferAnalyticsEvent.OutputObject>;
      TransferAnalytics: TypedContractEvent<TransferAnalyticsEvent.InputTuple, TransferAnalyticsEvent.OutputTuple, TransferAnalyticsEvent.OutputObject>;
    

      'TransferBlocked(address,address,uint256,string)': TypedContractEvent<TransferBlockedEvent.InputTuple, TransferBlockedEvent.OutputTuple, TransferBlockedEvent.OutputObject>;
      TransferBlocked: TypedContractEvent<TransferBlockedEvent.InputTuple, TransferBlockedEvent.OutputTuple, TransferBlockedEvent.OutputObject>;
    

      'TransferLimitUpdated(uint256,uint256)': TypedContractEvent<TransferLimitUpdatedEvent.InputTuple, TransferLimitUpdatedEvent.OutputTuple, TransferLimitUpdatedEvent.OutputObject>;
      TransferLimitUpdated: TypedContractEvent<TransferLimitUpdatedEvent.InputTuple, TransferLimitUpdatedEvent.OutputTuple, TransferLimitUpdatedEvent.OutputObject>;
    

      'TreasuryUpdated(address,address)': TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
      TreasuryUpdated: TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'UserActivity(address,string,uint256,uint256)': TypedContractEvent<UserActivityEvent.InputTuple, UserActivityEvent.OutputTuple, UserActivityEvent.OutputObject>;
      UserActivity: TypedContractEvent<UserActivityEvent.InputTuple, UserActivityEvent.OutputTuple, UserActivityEvent.OutputObject>;
    

      'VoteCast(uint256,address,bool,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    
    };
  }